### ISSUE TITLE
JAVASCRIPT OUR OF HEAP IN IONIC --PROD

### ISSUE THREAD

**Issue by samuelaj1** [ionic-team/ionic-app-scripts#1447] opened 2018-06-18 09:37 UTC
**AM USING MAPS IN MY PROJECT...I DONT KNOW WHETHER THAT IS THE CAUSE OF THE ISSUE**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

Running app-scripts build: --prod --platform android --target cordova[09:32:38]  build prod started ...
[09:32:38]  clean started ...
[09:32:38]  clean finished in 5 ms
[09:32:38]  copy started ...
[09:32:38]  deeplinks started ...
[09:32:39]  deeplinks finished in 415 ms
[09:32:39]  ngc started ...
[09:33:01]  ngc finished in 22.60 s[09:33:01]  preprocess started ...
[09:33:01]  preprocess finished in 1 ms
[09:33:01]  webpack started ...
[09:33:03]  copy finished in 24.39 s

<--- Last few GCs --->

  109977 ms: Mark-sweep 1344.6 (1435.0) -> 1344.6 (1435.0) MB, 1630.6 / 0.0 ms [allocation failure] [GC in old space re
quested].
  111602 ms: Mark-sweep 1344.6 (1435.0) -> 1344.6 (1435.0) MB, 1625.0 / 0.0 ms [allocation failure] [GC in old space re
quested].
  113330 ms: Mark-sweep 1344.6 (1435.0) -> 1356.7 (1412.0) MB, 1727.8 / 0.0 ms [last resort gc].
  114933 ms: Mark-sweep 1356.7 (1412.0) -> 1369.0 (1412.0) MB, 1602.2 / 0.0 ms [last resort gc].

<--- JS stacktrace --->

==== JS stack trace =========================================

Security context: 0x1919032cfb51 <JS Object>
    1: getOrCreateEmitNode(aka getOrCreateEmitNode) [/Applications/XAMPP/xamppfiles/htdocs/erranda/nativeMap/node_modules/typescript/lib/typescript.js:~49321] [pc=0x411948ec548] (this=0x191903204381 <undefined>,node=0xb1393dc9499 <an IdentifierObject with map 0x240f05354279>)
    2: setEmitFlags [/Applications/XAMPP/xamppfiles/htdocs/erranda/nativeMap/node_modules/typescript/lib/typescript.js:~...

FATAL ERROR: CALL_AND_RETRY_LAST Allocation failed - JavaScript heap out of memory
 1: node::Abort() [/usr/local/bin/node]
 2: node::FatalException(v8::Isolate*, v8::Local<v8::Value>, v8::Local<v8::Message>) [/usr/local/bin/node]
 3: v8::internal::V8::FatalProcessOutOfMemory(char const*, bool) [/usr/local/bin/node]
 4: v8::internal::Factory::NewFillerObject(int, bool, v8::internal::AllocationSpace) [/usr/local/bin/node]
 5: v8::internal::Runtime_AllocateInTargetSpace(int, v8::internal::Object**, v8::internal::Isolate*) [/usr/local/bin/node]
 6: 0x411947079a7
 7: 0x411948ec548
 8: 0x41196ca870f
Abort trap: 6

**Comment by mhartington** [comment] 2018-06-18 12:08
Closing as duplicate of 

https://github.com/ionic-team/ionic-app-scripts/issues/1247

**Closed by mhartington** 2018-06-18 12:08 UTC
