### ISSUE TITLE
proxy doesn't work on new ionic-app-scripts 2.0.0

### ISSUE THREAD

**Issue by Alberick** [ionic-team/ionic-app-scripts#1086] opened 2017-07-08 17:58 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
proxy doesn't work after upgrade, endpoints resolves with status code "304 Not Modified", response data is the content of the index.html

#### What behavior are you expecting?
proxied api should return my valid data

**Steps to reproduce:**
1. updated to app-scripts@2.0.0
2. add proxy to project
3. fire request to the proxied api.

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**
2.0.0

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)
$ ionic info

global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.1.2
    Ionic Framework                 : ionic-angular 3.5.0

System:

    Node       : v6.10.3
    OS         : Windows 10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 3.10.10

**Comment by Xepe** [comment] 2017-07-08 18:13
I have the same problem, I review the difference with the previous version and I found that if you removed this [line](https://github.com/ionic-team/ionic-app-scripts/blob/master/src/dev-server/http-server.ts#L50)  it works 

Regards

**Comment by mburger81** [comment] 2017-07-10 10:07
Yes I confirm, we have the same problem with app-scripts 2.0.

Proxy wan't work anymore
```
global packages:

    @ionic/cli-utils : 1.4.0
    Cordova CLI      : 7.0.1 
    Ionic CLI        : 3.4.0

local packages:

    @ionic/app-scripts              : 2.0.0
    @ionic/cli-plugin-cordova       : 1.4.0
    @ionic/cli-plugin-ionic-angular : 1.3.1
    Cordova Platforms               : android 6.2.3
    Ionic Framework                 : ionic-angular 3.5.0-201707061803

System:

    Node       : v6.11.0
    OS         : Linux 4.10
    Xcode      : not installed
    ios-deploy : not installed
    ios-sim    : not installed
    npm        : 5.1.0 

```

**Comment by gslender** [comment] 2017-07-10 11:55
yep..broken... proxy not working

**Comment by savanvadalia** [comment] 2017-07-10 13:11
yes, confirmed proxy is not working any more.

Gives this error in my case `SyntaxError: Unexpected token < in JSON at position 0` as the web api is not returning expected JSON and it seems to be parsing the html instead and producing this error.

**Comment by ricgil** [comment] 2017-07-10 13:54
Same here, and as @Xepe says, removing that line works.

**Comment by danbucholtz** [comment] 2017-07-10 16:47
This is fixed in `nightly`. I reverted the change to the http-server. That came in as a PR.

```
npm install @ionic/app-scripts@nightly
```

Thanks,
Dan

**Closed by danbucholtz** 2017-07-10 16:47 UTC

**Comment by janpio** [comment] 2017-07-11 14:09
After installing the nightly I unfortunately get 

```
> ionic serve -b --verbose
[DEBUG] Loading global plugin @ionic/cli-plugin-proxy
[DEBUG] Loading local plugin @ionic/cli-plugin-cordova
[DEBUG] Loading local plugin @ionic/cli-plugin-ionic-angular
[DEBUG] !!! ERROR ENCOUNTERED !!!
Error: Cannot find module 'fs-extra'
[DEBUG] Error: Cannot find module 'fs-extra'
        at Function.Module._resolveFilename (module.js:485:15)
        at Function.Module._load (module.js:437:25)
        at Module.require (module.js:513:17)
        at require (internal/module.js:11:18)
        at Object.<anonymous> (C:\Users\Jan\Documents\yatsa\node_modules\@ionic\app-scripts\dist\util\config.js:4:18)
        at Module._compile (module.js:569:30)
        at Object.Module._extensions..js (module.js:580:10)
        at Module.load (module.js:503:32)
        at tryModuleLoad (module.js:466:12)
        at Function.Module._load (module.js:458:3)

```
