### ISSUE TITLE
"npm run ionic:build --prod" includes local filesystem path in output

### ISSUE THREAD

**Issue by ammulder** [ionic-team/ionic-app-scripts#1082] opened 2017-07-06 16:24 UTC
#### Short description of the problem:

In my Ionic 3 project I run:
```
$ npm run ionic:build --prod
```
Then look at this:
```
$ grep -r ammulder www
www/build/0.main.js://# sourceMappingURL=/Users/ammulder/dev/myproject/www/build/0.main.js.map
www/build/main.js://# sourceMappingURL=/Users/ammulder/dev/myproject/www/build/main.js.map
```

#### What behavior are you expecting?

Not to see a path on my local filesystem in the output code

**Steps to reproduce:**
1. npm run ionic:build --prod
2. grep -r ((a word in the path on your computer)) www/
3. Don't get nothing

**Which <span>@</span>ionic/app-scripts version are you using?**
1.3.12

**Comment by DavidStrausz** [comment] 2017-07-06 22:57
Duplicate of #856

**Comment by jgw96** [comment] 2017-07-20 16:48
Hello all! I am going to close this as a duplicate of #856

**Closed by jgw96** 2017-07-20 16:48 UTC
