### ISSUE TITLE
Runtime Error - Cannot read property 'indexOf' of null

### ISSUE THREAD

**Issue by AlessandroSchneiderSignUP** [ionic-team/ionic-app-scripts#966] opened 2017-05-05 13:22 UTC
**Note: for support questions, please use one of these channels:**

https://forum.ionicframework.com/
http://ionicworldwide.herokuapp.com/

#### Short description of the problem:
It happens in 50% of the times I serve ionic.

#### What behavior are you expecting?
I expect the error not to occur.

**Steps to reproduce:**
1. ionic serve
2. open browser

```
insert any relevant code between the above and below backticks
```

**Which @ionic/app-scripts version are you using?**

**Other information:** (e.g. stacktraces, related issues, suggestions how to fix, stackoverflow links, forum links, etc)

Stack
TypeError: Cannot read property 'indexOf' of null
    at Tab.NavControllerBase._cleanup (http://localhost:8100/build/main.js:46089:59)
    at Tab.NavControllerBase._transitionFinish (http://localhost:8100/build/main.js:45991:18)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9655)
    at Object.onInvoke (http://localhost:8100/build/main.js:38985:37)
    at t.invoke (http://localhost:8100/build/polyfills.js:3:9606)
    at e.run (http://localhost:8100/build/polyfills.js:3:7019)
    at NgZone.run (http://localhost:8100/build/main.js:38854:62)
    at Array.<anonymous> (http://localhost:8100/build/main.js:45939:25)
    at MDTransition.Animation._didFinish (http://localhost:8100/build/main.js:11897:29)
    at MDTransition.Animation._playProgress (http://localhost:8100/build/main.js:11254:18)
    at MDTransition.Animation._playDomInspect (http://localhost:8100/build/main.js:11220:14)

Ionic Framework: 2.2.0
Ionic App Scripts: 1.1.4
Angular Core: 2.4.8
Angular Compiler CLI: 2.4.8
Node: 7.9.0
OS Platform: OS X Yosemite
Navigator Platform: MacIntel
User Agent: Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/57.0.2987.133 Safari/537.36

**Comment by danbucholtz** [comment] 2017-05-05 13:25
@AlessandroSchneiderSignUP,

Can you upload a repo where I can recreate this?

Thanks,
Dan

**Comment by AlessandroSchneiderSignUP** [comment] 2017-05-05 13:34
Hi Dan,

thanks for your reply. I have sent you an invitation to the private repo.

Thank you!

**Comment by dm-grinko** [comment] 2017-05-24 13:34
Hi guys.
https://monosnap.com/file/nS4CakuwwrnHrz5q3GZcbEE5l1smEd
How to solve it?

**Comment by AlessandroSchneiderSignUP** [comment] 2017-05-26 08:40
HI dm-grinko,

I found the issue. In my case it happened due to ngIfs in the tabs template. I therefore got several views opened the same time. And then in the cleaning process of the views something got wrong. Check this by logging the console in your views.

**Comment by danbucholtz** [comment] 2017-06-28 04:24
Hi, it seems like it was a coding mistake and not an app-scripts issue, so I am going to close this issue. Please let me know if I'm mistaken and I need to re-open.

Thanks,
Dan

**Closed** 2017-06-28 04:24 UTC

**Comment by issy123** [comment] 2018-06-08 11:23
`Hi, it seems like it was a coding mistake and not an app-scripts issue, so I am going to close this issue. `

Hi Dan,

I know this is a 'coding mistake', but it is hard to trace this back to what caused it.
It would be nice if either the stacktrace shows what the cause was or ionic should give an error message. The ionic framework itself shouldn't be crashing

**Comment by GiselaMD** [comment] 2018-12-31 14:52
I'm having this issue and my app used to work, don't know if it is coding mistake. Could someone help me?

It only happens with iOS

**Comment by dm-grinko** [comment] 2018-12-31 14:55
@GiselaMD the indexOf is method of Array. You will get this error if you use it on other object or on undefined value.

**Comment by GiselaMD** [comment] 2018-12-31 14:58
@dm-grinko but I didn't have this error before and why does it only happens on iOS?
